const dados = [
  {
      "id": "1",
      "empresa": "AGULHAS NEGRAS - RJ",
      "consultor": "João",
      "panl": 1,
      "hs": 0,
      "horaMedia": 0,
      "mensalidade": 0,
      "totalMensalDoCliente": 19.15,
      "totalAcumuladoCliente": 179.54,
      "mensalidadeNova": 0,
      "horaMediaNova": 0,
      "horasR": 0,
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": 0,
      "integracao": "25/02/2021",
      "dataChurn": "01/02/2024",
      "mses": 35.7,
      "dias": 1071,
      "setUpMes": 0,
      "heraMes": 0,
      "bpoMes": 0,
      "finpetMes": 19.15,
      "setUpAcum": 0,
      "heraAcum": 0,
      "bpoAcum": 0,
      "finpetAcum": 179.54,
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "RJ",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": 15,
      "status": "Churn",
      "pontoZero": 0,
      "sistemaOperacional": "Simplesvet",
      "oficinaMetodologia": "S",
      "diagnosticoRealizado": "N",
      "analiseCritica": "N",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "2",
      "empresa": "ALLIANCE CARE - SP",
      "consultor": "Leandro",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "07/10/2020",
      "dataChurn": "31/12/2021",
      "mses": "15",
      "dias": "450",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SP",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "",
      "diagnosticoRealizado": "",
      "analiseCritica": "",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "3",
      "empresa": "ALMIR TAVARES - AL",
      "consultor": "Evaldo",
      "panl": "4",
      "hs": "4",
      "horaMedia": " R$ 672,50 ",
      "mensalidade": "R$ 2.690,00",
      "totalMensalDoCliente": " R$ 3.176,20 ",
      "totalAcumuladoCliente": " R$ 127.959,46 ",
      "mensalidadeNova": " R$ 2.677,00 ",
      "horaMediaNova": " R$ 400,00 ",
      "horasR": " R$ 1.600,00 ",
      "pnlR": " R$ 399,00 ",
      "dreR": " R$ 399,00 ",
      "raVendasR": " R$ 279,00 ",
      "raClientesR": " R$ -   ",
      "raPetShopR": " R$ -   ",
      "raFluxoDeCaixaR": " R$ -   ",
      "totalDoContrato24M": "R$ 8.531,13",
      "integracao": "09/07/2020",
      "dataChurn": "",
      "mses": "44,83",
      "dias": "1344,9",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 486,20",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ 1.050,00 ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ 6.320,59 ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "AL",
      "rg": "NE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Fixo",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "Simplesvet",
      "oficinaMetodologia": "N",
      "diagnosticoRealizado": "N",
      "analiseCritica": "N",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "4",
      "empresa": "ALPRIVET - SP",
      "consultor": "Lee",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "19/09/2019",
      "dataChurn": "01/07/2021",
      "mses": "21,7",
      "dias": "651",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SP",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "",
      "diagnosticoRealizado": "",
      "analiseCritica": "",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "5",
      "empresa": "AMI - SC",
      "consultor": "Lee",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "17/02/2022",
      "dataChurn": "30/10/2022",
      "mses": "8,5",
      "dias": "255",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SC",
      "rg": "S",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "",
      "diagnosticoRealizado": "",
      "analiseCritica": "",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "6",
      "empresa": "AMIGO PET - BA",
      "consultor": "Artur",
      "panl": "1",
      "hs": "2",
      "horaMedia": " R$ 445,00 ",
      "mensalidade": "R$ 890,00",
      "totalMensalDoCliente": " R$ 953,24 ",
      "totalAcumuladoCliente": " R$ 39.349,86 ",
      "mensalidadeNova": " R$ 1.598,00 ",
      "horaMediaNova": " R$ 400,00 ",
      "horasR": " R$ 800,00 ",
      "pnlR": " R$ 399,00 ",
      "dreR": " R$ 399,00 ",
      "raVendasR": " R$ -   ",
      "raClientesR": " R$ -   ",
      "raPetShopR": " R$ -   ",
      "raFluxoDeCaixaR": " R$ -   ",
      "totalDoContrato24M": "R$ 8.192,23",
      "integracao": "06/01/2021",
      "dataChurn": "",
      "mses": "38,8",
      "dias": "1163,9",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 63,24",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ 4.000,00 ",
      "finpetAcum": " R$ 822,09 ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "BA",
      "rg": "NE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Fixo",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "Simplesvet",
      "oficinaMetodologia": "N",
      "diagnosticoRealizado": "N",
      "analiseCritica": "N",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "7",
      "empresa": "AMIGO PET - SP",
      "consultor": "Lee",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "04/08/2021",
      "dataChurn": "30/10/2022",
      "mses": "15,07",
      "dias": "452",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SP",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "",
      "diagnosticoRealizado": "",
      "analiseCritica": "",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "8",
      "empresa": "AMOR CAO E GATO - SP",
      "consultor": "Amanda",
      "panl": "1",
      "hs": "5",
      "horaMedia": " R$ 200,00 ",
      "mensalidade": "R$ 1.000,00",
      "totalMensalDoCliente": " R$ 1.063,31 ",
      "totalAcumuladoCliente": " R$ 31.518,22 ",
      "mensalidadeNova": " R$ 3.077,00 ",
      "horaMediaNova": " R$ 400,00 ",
      "horasR": " R$ 2.000,00 ",
      "pnlR": " R$ 399,00 ",
      "dreR": " R$ 399,00 ",
      "raVendasR": " R$ 279,00 ",
      "raClientesR": " R$ -   ",
      "raPetShopR": " R$ -   ",
      "raFluxoDeCaixaR": " R$ -   ",
      "totalDoContrato24M": "R$ 17.304,76",
      "integracao": "06/09/2021",
      "dataChurn": "",
      "mses": "30,7",
      "dias": "920,9",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 63,31",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ 822,98 ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SP",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "15%",
      "status": "Fat",
      "pontoZero": "R$ 122.500,00",
      "sistemaOperacional": "Simplesvet",
      "oficinaMetodologia": "S",
      "diagnosticoRealizado": "N",
      "analiseCritica": "S",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "9",
      "empresa": "AMOR DE BICHOS - MG",
      "consultor": "Lee",
      "panl": "3",
      "hs": "3",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ 2.880,00 ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "24/08/2021",
      "dataChurn": "30/03/2023",
      "mses": "19,43",
      "dias": "583",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ 2.880,00 ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "MG",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "MKT",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "Simplesvet",
      "oficinaMetodologia": "N",
      "diagnosticoRealizado": "N",
      "analiseCritica": "N",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "10",
      "empresa": "AMORPET - DF",
      "consultor": "Amanda",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "13/12/2022",
      "dataChurn": "15/11/2023",
      "mses": "11,23",
      "dias": "337",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "DF",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "Simplesvet",
      "oficinaMetodologia": "S",
      "diagnosticoRealizado": "N",
      "analiseCritica": "N",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "11",
      "empresa": "ANIMA ANIMAL",
      "consultor": "Lee",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "07/04/2020",
      "dataChurn": "01/12/2020",
      "mses": "7,93",
      "dias": "238",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "RJ",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "",
      "diagnosticoRealizado": "",
      "analiseCritica": "",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "12",
      "empresa": "ANIMAL",
      "consultor": "Lee",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "27/09/2022",
      "dataChurn": "30/10/2022",
      "mses": "1,1",
      "dias": "33",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SP",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "",
      "diagnosticoRealizado": "",
      "analiseCritica": "",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "13",
      "empresa": "ANIMAL CENTER",
      "consultor": "Evaldo",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "12/09/2019",
      "dataChurn": "31/12/2021",
      "mses": "28,03",
      "dias": "841",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SP",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "",
      "diagnosticoRealizado": "",
      "analiseCritica": "",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "14",
      "empresa": "ANIMAL DOCTORS",
      "consultor": "Amanda",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "07/06/2022",
      "dataChurn": "30/10/2022",
      "mses": "4,83",
      "dias": "145",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SP",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "N",
      "diagnosticoRealizado": "N",
      "analiseCritica": "N",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "15",
      "empresa": "ANIMALE - SP",
      "consultor": "Lee",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ -   ",
      "totalAcumuladoCliente": " R$ -   ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "04/08/2022",
      "dataChurn": "04/08/2022",
      "mses": "0",
      "dias": "0",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 0,00",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ -   ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "SP",
      "rg": "SE",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Churn",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "",
      "oficinaMetodologia": "",
      "diagnosticoRealizado": "",
      "analiseCritica": "",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  },
  {
      "id": "16",
      "empresa": "ANIMALLIA - MT",
      "consultor": "Amanda",
      "panl": "0",
      "hs": "0",
      "horaMedia": " R$ -   ",
      "mensalidade": "R$ 0,00",
      "totalMensalDoCliente": " R$ 47,36 ",
      "totalAcumuladoCliente": " R$ 556,77 ",
      "mensalidadeNova": " R$ -   ",
      "horaMediaNova": "",
      "horasR": " R$ -   ",
      "pnlR": "",
      "dreR": "",
      "raVendasR": "",
      "raClientesR": "",
      "raPetShopR": "",
      "raFluxoDeCaixaR": "",
      "totalDoContrato24M": "R$ 0,00",
      "integracao": "19/01/2022",
      "dataChurn": "01/06/2022",
      "mses": "4,43",
      "dias": "133",
      "setUpMes": "R$ 0,00",
      "heraMes": "R$ 0,00",
      "bpoMes": "R$ 0,00",
      "finpetMes": "R$ 47,36",
      "setUpAcum": "R$ 0,00",
      "heraAcum": " R$ -   ",
      "bpoAcum": " R$ -   ",
      "finpetAcum": " R$ 556,77 ",
      "proprietarioGestor": "",
      "telefone": "",
      "endereco": "",
      "uf": "GO",
      "rg": "CO",
      "fatMedioMensal": "AUSENTE",
      "variavel": "0%",
      "status": "Finpet",
      "pontoZero": "R$ 0,00",
      "sistemaOperacional": "Simplesvet",
      "oficinaMetodologia": "N",
      "diagnosticoRealizado": "N",
      "analiseCritica": "N",
      "parametrizacaoDeSistemas": "",
      "precificacao": "",
      "atendimentoRecEpo": "",
      "atendimentoRecInativos": "",
      "planejamentoEstrategico": "",
      "identidadeCorporativa": "",
      "valuation": "",
      "pesquisaDeClima": "",
      "pesquisaNps": "",
      "analiseDePerfil": "",
      "pesquisaDeMercado": ""
  }
];

export default dados;